[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["private_docs/**"]

[[redirects]]
  from = "/colistiers/*"
  to = "/.netlify/functions/colistiers"
  status = 200
  force = true

[[redirects]]
  from = "/documents.html"
  to = "/colistiers/documents.html"
  status = 301
  force = true

[[redirects]]
  from = "/documents"
  to = "/colistiers/documents.html"
  status = 301
  force = true

[[headers]]
  for = "/assets/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/video/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=604800"
